name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
 
jobs:
  build_and_test:
    runs-on: ubuntu-latest
 
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Build and Test
        run: |
          npm ci
          npm run build
          npm run test

      - name: Check dist/ files match
        run: |
          git diff --exit-code dist/ || (echo "❌ dist/ files don't match the committed version" && exit 1)
